# Generated by Django 3.1.5 on 2021-01-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_professor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='email',
        ),
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
    ]
