# Generated by Django 3.1.5 on 2021-01-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210114_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='grade_tree',
            field=models.FileField(null=True, upload_to='uploads/grade_tree/'),
        ),
        migrations.AddField(
            model_name='test',
            name='qp_tree',
            field=models.FileField(null=True, upload_to='uploads/qp_tree'),
        ),
    ]
