# Generated by Django 3.1.5 on 2021-01-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210115_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='answer_scripts',
            field=models.FileField(null=True, upload_to='uploads/answer_scripts/'),
        ),
        migrations.AlterField(
            model_name='test',
            name='consolidated_marksheet',
            field=models.FileField(null=True, upload_to='uploads/marksheets/'),
        ),
    ]
