# Generated by Django 3.1.5 on 2021-02-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210115_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='name',
            field=models.CharField(default='31222', max_length=50),
            preserve_default=False,
        ),
    ]
