# Generated by Django 3.1.5 on 2021-02-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_submission_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='handwriting_verified',
            field=models.BooleanField(null=True),
        ),
    ]
