# Generated by Django 3.1.5 on 2021-02-23 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_submission_handwriting_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('handwriting_model', models.FileField(null=True, upload_to='uploads/handwriting/')),
            ],
        ),
    ]
