# Generated by Django 3.1.5 on 2021-02-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210228_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='handwriting_model_path',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
